<?php

namespace App\Models;

use App\Enums\SlotStatus;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\DB;

class AvailableSlot extends Model
{
    protected $fillable = [
        'start_time',
        'end_time',
        'status',
        'schedule_template_id',
        'source',
    ];

    protected $casts = [
        'status' => SlotStatus::class,
        'start_time' => 'datetime',
        'end_time' => 'datetime',
    ];

    public function scopeAvailable($query)
    {
        return $query->where('status', 'available')
                     ->where('start_time', '>', now())
                     ->orderBy('start_time', 'asc');
    }

    /**
     * Scope to filter by time of day (morning, afternoon, evening)
     */
    public function scopeTimeOfDay($query, $period)
    {
        $ranges = [
            'morning'   => [6, 12],
            'afternoon' => [12, 17],
            'evening'   => [17, 21],
        ];

        if (! isset($ranges[$period])) {
            return $query;
        }

        [$from, $to] = $ranges[$period];

        $hourExpr = DB::getDriverName() === 'sqlite'
            ? "CAST(strftime('%H', start_time) AS INTEGER)"
            : 'HOUR(start_time)';

        return $query->whereRaw("$hourExpr >= ? AND $hourExpr < ?", [$from, $to]);
    }

    /**
     * Scope to filter by day of week (database-agnostic, Hungarian calendar: Monday=1)
     *
     * @param array $days Array of day numbers (1=Monday, 2=Tuesday, ..., 7=Sunday)
     */
    public function scopeDayOfWeek($query, array $days)
    {
        $isSqlite = DB::getDriverName() === 'sqlite';

        // Convert Hungarian calendar days to driver-native values
        $nativeDays = array_map(function ($day) use ($isSqlite) {
            if ($isSqlite) {
                // strftime('%w'): 0=Sunday, 1=Monday … 6=Saturday
                return $day == 7 ? 0 : $day;
            }

            // MySQL DAYOFWEEK(): 1=Sunday, 2=Monday … 7=Saturday
            return $day == 7 ? 1 : $day + 1;
        }, $days);

        $dayExpr = $isSqlite
            ? "CAST(strftime('%w', start_time) AS INTEGER)"
            : 'DAYOFWEEK(start_time)';

        $placeholders = implode(',', array_fill(0, count($nativeDays), '?'));

        return $query->whereRaw("$dayExpr IN ($placeholders)", $nativeDays);
    }

    /**
     * Get the schedule template that generated this slot.
     */
    public function scheduleTemplate(): BelongsTo
    {
        return $this->belongsTo(ScheduleTemplate::class);
    }

    /**
     * Scope to filter auto-generated slots.
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('source', 'auto');
    }

    /**
     * Scope to filter manually created slots.
     */
    public function scopeManual($query)
    {
        return $query->where('source', 'manual');
    }
}
