<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ScheduleTemplate extends Model
{
    protected $fillable = [
        'name',
        'day_of_week',
        'start_time',
        'end_time',
        'slot_duration_minutes',
        'break_between_minutes',
        'is_active',
        'effective_from',
        'effective_until',
        'max_weeks_ahead',
    ];

    protected $casts = [
        'is_active' => 'boolean',
        'effective_from' => 'date',
        'effective_until' => 'date',
        'day_of_week' => 'integer',
        'slot_duration_minutes' => 'integer',
        'break_between_minutes' => 'integer',
        'max_weeks_ahead' => 'integer',
    ];

    /**
     * Get the available slots generated by this template.
     */
    public function slots(): HasMany
    {
        return $this->hasMany(AvailableSlot::class);
    }

    /**
     * Scope to filter only active templates.
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope to filter templates for a specific day of week.
     */
    public function scopeForDay($query, int $dayOfWeek)
    {
        return $query->where('day_of_week', $dayOfWeek);
    }

    /**
     * Get the human-readable day name from day_of_week.
     */
    public function getDayNameAttribute(): string
    {
        $days = [
            0 => 'Sunday',
            1 => 'Monday',
            2 => 'Tuesday',
            3 => 'Wednesday',
            4 => 'Thursday',
            5 => 'Friday',
            6 => 'Saturday',
        ];

        return $days[$this->day_of_week] ?? 'Unknown';
    }

    /**
     * Check if this template is effective on a given date.
     */
    public function isEffectiveOn(Carbon $date): bool
    {
        if ($this->effective_from && $date->lt($this->effective_from)) {
            return false;
        }

        if ($this->effective_until && $date->gt($this->effective_until)) {
            return false;
        }

        return true;
    }
}
